version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-26-nov-2023/final-projects/cannabees.cloud:latest
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend #right side is container and left side is local machine
    command: 'sh /scripts/dev.sh'
    env_file:
      - ./envs/dev.env
    depends_on:
      - postgres

  celery:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-26-nov-2023/final-projects/cannabees.cloud:latest
    volumes:
      - ./backend:/backend  # Ensure Celery has access to your Django project's code
    command: celery -A project worker --loglevel=info  # Replace your_project_name with your actual project name
    env_file:
      - ./envs/dev.env
    depends_on:
      - postgres  # Assuming Celery needs to access the database

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - '5555:5432'
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: