# Generated by Django 5.0.1 on 2024-02-20 15:56

import agenda_point.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=agenda_point.models.agenda_files_path)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
