# Generated by Django 5.0.1 on 2024-02-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda_point', '0001_initial'),
        ('meeting', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendapoint',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_points', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='agendapoint',
            name='voting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_point', to='voting.voting'),
        ),
        migrations.AddField(
            model_name='agendafile',
            name='agenda_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_files', to='agenda_point.agendapoint'),
        ),
    ]
