# Generated by Django 5.0.1 on 2024-02-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_point', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendapoint',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='agendapoint',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
