# Generated by Django 5.0.1 on 2024-02-20 15:56

import django.contrib.postgres.fields
import meeting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('meeting_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('meeting_reminders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=15), blank=True, default=list, size=None)),
                ('template', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=meeting.models.files_path)),
            ],
        ),
    ]
